import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source = readFileSync(new URL('../../public/js/grab-overlay.js', import.meta.url), 'utf8');
const {freshWallQr, drawGrabOverlay} = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const det = {active_cam:'WALL', bbox:[100,100,80,80],frame_w:640,frame_h:480,method:'yolo_qr',confidence:.8,data:'C'};
const telemetry = {qr_vision:det,vision_receipts:{qr_vision:{age:.2}}};
assert.equal(freshWallQr(telemetry,.5),det);
assert.equal(freshWallQr(telemetry,.9),null);
assert.equal(freshWallQr({...telemetry,qr_vision:{...det,active_cam:'BOTTOM'}}),null);
assert.equal(freshWallQr({...telemetry,vision_receipts:{}}),null);
assert.equal(freshWallQr({...telemetry,qr_vision:{...det,bbox:[NaN,0,10,10]}}),null);
const region={...det,method:'yolo_qr_region',data:undefined};
assert.equal(freshWallQr({...telemetry,qr_region:region,vision_receipts:{qr_vision:{age:.3},qr_region:{age:.1}}}),region);
const labels=[], rectangles=[];
const ctx = new Proxy({}, {get:(_,key)=> (...args)=> {if(key==='fillText') labels.push(args[0]);if(key==='strokeRect')rectangles.push(args);},set:()=>true});
const canvas={getContext:()=>ctx};
const img={naturalWidth:1280,naturalHeight:720,getBoundingClientRect:()=>({width:640,height:360})};
drawGrabOverlay(canvas,img,null,[.25,.1,.75,.8],null,det);
assert.ok(labels.includes('YOLO QR terbaca: C'));
assert.deepEqual(rectangles.at(-1),[100,75,80,60]);
labels.length=0;
drawGrabOverlay(canvas,img,null,[.25,.1,.75,.8],null,region);
assert.ok(labels.includes('YOLO QR terdeteksi · belum terbaca'));
console.log('QR overlay: camera, expiry, source coordinates, decoded/region labels PASS');
